[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
image = { version = "0.25.1", features = ["png", "rayon"], default-features = false }
rayon = "1.10.0"
krnl = "0.1.1"
clap = { version = "4.4", features = ["derive"] }
